-- Term data
insert into Term (term) values ('Spring 2019');
insert into Term (term) values ('Summer 2019');
insert into Term (term) values ('Fall 2020');

-- Person data
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Ferdy', 'Danièle', 'Damato');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Salli', 'Célia', 'Allsop');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Theresa', 'Camélia', 'O''Donohue');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Franny', 'Audréanne', 'Goodwell');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Nathalia', 'Maëlle', 'Romayne');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Kathe', 'Crééz', 'Scroggie');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Wileen', 'Esbjörn', 'Borrill');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Flint', 'Mylène', 'Godball');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Eward', 'Zoé', 'Hunsworth');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Marlowe', 'Vérane', 'Sherborn');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Nicholle', 'Dù', 'Vertey');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Terencio', null, 'Le Pruvost');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Tiffany', 'Lyséa', 'Matelaitis');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Denny', null, 'McClaren');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Persis', 'Angèle', 'Ayer');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Meade', 'Maëline', 'Dare');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Alec', 'Marlène', 'Jumont');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Linn', 'Adélie', 'Stannislawski');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Glennie', 'Cécilia', 'Gerardot');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Misti', 'Geneviève', 'Nern');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Teodora', 'Jú', 'Posselow');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Yancy', 'Laïla', 'Flude');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Bone', 'Zoé', 'Scroxton');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Elisa', 'Eléa', 'MacParland');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Blithe', 'Clémentine', 'Volonte');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Jessamine', 'Loïca', 'Antoniottii');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Elisabet', 'Séréna', 'Coan');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Shirlee', 'Anaïs', 'Waine');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Stinky', 'Mélys', 'Heineking');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Juliet', 'Salomé', 'Castrillo');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Caitrin', 'Cloé', 'O''Hagerty');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Verne', 'Nélie', 'Bayldon');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Terrill', 'Léandre', 'Surmon');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Maudie', 'Lorène', 'Janodet');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Batholomew', 'Pò', 'Millgate');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Virgil', 'Valérie', 'Leggs');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Frazer', 'Pål', 'Sans');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Alexandr', 'Desirée', 'Cordner');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Peirce', 'Joséphine', 'Rustidge');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Homer', 'Esbjörn', 'McRae');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Minny', 'Bénédicte', 'Fleming');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Maxie', 'Marie-françoise', 'Gavriel');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Nikolaus', 'Séréna', 'Krop');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Laurice', 'Angèle', 'Stilgo');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Carroll', 'Kù', 'D''Oyly');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Felic', 'Anaël', 'Venners');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Emalia', 'Angèle', 'Hasell');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Garvey', 'Håkan', 'Gilson');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Liane', 'Laurélie', 'Fludgate');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Rosie', 'Maïly', 'Duckitt');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Aksel', 'Andréanne', 'Pedden');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Goldy', null, 'Guillem');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Torry', null, 'Growy');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Chrissie', 'Méline', 'Littrick');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Loutitia', 'Géraldine', 'Dobel');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Keane', 'Séréna', 'Bracci');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Nealon', 'Eléonore', 'Hamlyn');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Andros', null, 'Wartnaby');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Jeffy', 'Chloé', 'Didsbury');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Inness', null, 'Isley');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Madison', 'Mélia', 'Treasure');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Pauly', null, 'Stack');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Aron', null, 'Gianolini');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Murial', 'Clélia', 'Hamel');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Sadye', 'Cunégonde', 'Astall');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Hildy', null, 'Cottem');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Claiborn', 'Océane', 'Campkin');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Siward', 'Estève', 'Shewery');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Diane-marie', 'Bénédicte', 'Faltin');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Clarissa', null, 'Sothern');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Wyndham', 'Solène', 'Skoggings');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Joachim', 'Sòng', 'Stachini');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Jeanelle', 'Mégane', 'Gilkison');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Jojo', 'Léone', 'Yaneev');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Aldus', 'Hélène', 'O''Nions');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Maiga', 'Lyséa', 'Kenningham');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Laney', null, 'Folliss');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Reynard', 'Ruì', 'Tonepohl');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Brandon', 'Michèle', 'Rulten');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Tobe', null, 'Swede');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Thornton', 'Léonore', 'Arnaudon');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Urbanus', 'Marylène', 'Plows');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Netta', null, 'Folcarelli');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Piper', null, 'Borel');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Gaspar', 'Estève', 'McAuliffe');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Shalom', 'Anaëlle', 'Hatje');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Andrea', 'Danièle', 'Seyers');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Bernete', 'Renée', 'Brushneen');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Evelyn', null, 'Tristram');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Amalie', 'Chloé', 'Casse');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Tamarra', null, 'Britian');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Lenard', null, 'De Vaux');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Chantalle', null, 'Averies');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Arnaldo', 'Dù', 'Enrique');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Noami', 'Marie-hélène', 'Scudders');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Adolf', null, 'Posvner');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Hastings', 'Chloé', 'Wackly');
insert into Person (rank, first_name, middle_name, last_name) values ('STAFF', 'Leonelle', 'Anaël', 'Gatus');
insert into Person (rank, first_name, middle_name, last_name) values ('STUDENT', 'Porter', 'Josée', 'Krolak');
insert into Person (rank, first_name, middle_name, last_name) values ('FACILITY', 'Jobina', null, 'Coppard');

-- Class data
insert into Class (name, room_number, period, term) values ('mauris', 'RF 6606-33 C', 7, 1);
insert into Class (name, room_number, period, term) values ('congue eget', 'FL 9227-78 J', 3, 1);
insert into Class (name, room_number, period, term) values ('ante', 'MH 8022-64 R', 1, 1);
insert into Class (name, room_number, period, term) values ('congue', 'QG 2216-97 B', 5, 1);
insert into Class (name, room_number, period, term) values ('amet', 'UG 9250-60 D', 6, 1);
insert into Class (name, room_number, period, term) values ('magna', 'UZ 9682-82 M', 5, 1);
insert into Class (name, room_number, period, term) values ('faucibus', 'DX 4146-27 W', 3, 2);
insert into Class (name, room_number, period, term) values ('ultrices', 'EP 5198-40 R', 1, 3);
insert into Class (name, room_number, period, term) values ('magna vulputate', 'BT 3417-90 Q', 2, 3);
insert into Class (name, room_number, period, term) values ('placerat', 'TJ 5220-72 V', 4, 1);

-- Class Person data
insert into PersonClass (person_id, class_id) values (6, 8);
insert into PersonClass (person_id, class_id) values (12, 3);
insert into PersonClass (person_id, class_id) values (9, 1);
insert into PersonClass (person_id, class_id) values (12, 2);
insert into PersonClass (person_id, class_id) values (30, 8);
insert into PersonClass (person_id, class_id) values (12, 2);
insert into PersonClass (person_id, class_id) values (9, 7);
insert into PersonClass (person_id, class_id) values (6, 2);
insert into PersonClass (person_id, class_id) values (24, 1);
insert into PersonClass (person_id, class_id) values (24, 8);
insert into PersonClass (person_id, class_id) values (12, 6);
insert into PersonClass (person_id, class_id) values (3, 10);
insert into PersonClass (person_id, class_id) values (6, 4);
insert into PersonClass (person_id, class_id) values (3, 4);
insert into PersonClass (person_id, class_id) values (9, 9);